/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
    
    // Apache Lucene dependencies for indexing and search
    implementation("org.apache.lucene:lucene-core:10.2.1")
    implementation("org.apache.lucene:lucene-analyzers-common:8.11.4")
    implementation("org.apache.lucene:lucene-queryparser:10.2.1")
    implementation("org.apache.lucene:lucene-highlighter:10.2.1")

    
    // Apache OpenNLP for natural language processing
    implementation("org.apache.opennlp:opennlp-tools:2.5.4")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.IR.SearchEngine.app.App"
}

tasks.named<JavaExec>("run") {
    standardInput = System.`in`
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
